#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF

Usage:

\`\`\`bash

  $BIN FILE

\`\`\`bash

Order lines that ensure that the dependencies are first on the list.

\`\`\`

Example:

\`\`\`bash

  cat deploy/update.awx

    job_template/wst_wol_v0.1.0.json
    project/ansible_wst_v0.1.0.json
    inventory/wst.json
    credential/ssh_wst.json

  $BIN deploy/update.awx

    credential/ssh_wst.json
    project/ansible_wst_v0.1.0.json
    inventory/wst.json
    job_template/wst_wol_v0.1.0.json

\`\`\`
EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

TMPI='NONE'

if [[ ! -t 0 ]]
then

  TMPI="$(mktemp)"

  true > "$TMPI"

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

fi

[[ -z "$1"    ]] || TMPI="$1"
[[ -e "$TMPI" ]] || die "NOT FOUND FILE: $TMPI"

for i in credential project inventory job_template
do
  grep "^$i" "$TMPI" | sort
done
