#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN VERSION_FILE [TEAM]

\`\`\`

Grant use and execute permissions to a _project_, _job template_ and
_workflow_ defined in version file to _team_.

\`\`\`bash

 $BIN wfw_pve_v0.1.0.version devops

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

TEAM="$DEFAULT_TEAM"

[[ -z "$1" ]] && die 'EMPTY VERSION_FILE'
VERSION="$1"

[[ ! -s "$1" ]] && die "EMPTY FILE $VERSION"

[[ -n "$2" ]] && TEAM="$2"
[[ -z "$TEAM" ]] && die "EMPTY TEAM"

for ITEM in project job_template workflow
do
  grep "^$ITEM" "$VERSION" | while read -r _ NAME _
  do
    [[ "$ITEM" = 'project'      ]] && GRANT='project-use'
    [[ "$ITEM" = 'job_template' ]] && GRANT='job-template-execute'
    [[ "$ITEM" = 'workflow'     ]] && GRANT='workflow-execute'
    echo "GRANT $GRANT $NAME $TEAM"
    "awx-grant-$GRANT" "$NAME" "$TEAM"
  done
done
