#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:
  $BIN

Description

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die "EMPTY INVENTORY_SOURCE"
[[ -z "$2" ]] && die "EMPTY KEY"
[[ -z "$3" ]] && die "EMPTY NEW_VALUE"

INVENTORY_SOURCE="$1"
KEY="$2"
NEW_VALUE="$3"

JSON=$(mktemp --suffix .json)

awx-cli host get             \
  --format json              \
  --name "$INVENTORY_SOURCE" > "$JSON" 2>/dev/null

YAML=$(mktemp --suffix .yml)

[[ -s "$JSON" ]] || exit 1

jq -r .variables "$JSON" > "$YAML" 2>/dev/null

VALUE="$(yq -r ".$KEY" "$YAML" | grep -vi null)"

[[ "$VALUE" = "$NEW_VALUE" ]] && success "ALREADY SET $KEY = $NEW_VALUE"

jq -r ".$KEY = \"$NEW_VALUE\"" "$YAML" | sponge "$YAML" || die "REPLACE"

awx-cli host modify        \
  --inventory "$INVENTORY" \
  --variables "@$YAML"     \
  -n "$HOST"               || die "MODIFY"
:
rm -f "$JSON"
rm -f "$YAML"
