#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2024 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2024 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ "$BASH_DEBUG" -eq 1 ]] && set -x

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN INVENTORY

\`\`\`

Generate CMDB (Configuration Management Database) with \`ansible-cmdb\`
for all hosts in an inventory by getting _ansible facts_ from an _AWX_
instance using \`awx-cli\`.

Example:

\`\`\`bash

  $BIN wst dev

  FOUND    1 GROUPS IN INVENTORY wst MATCH WITH REGEX .*
  FOUND    6 HOSTS IN INVENTORY wst MATCH WITH GROUP dev
  FOUND   88 FACTS FOR HOST wst-8CC0125Y5S IN INVENTORY wst GROUP dev
  FOUND   88 FACTS FOR HOST wst-8CC0125YCV IN INVENTORY wst GROUP dev
  FOUND    0 FACTS FOR HOST wst-8CC0125YG0 IN INVENTORY wst GROUP dev
  FOUND   88 FACTS FOR HOST wst-8CC0125YSV IN INVENTORY wst GROUP dev
  FOUND   88 FACTS FOR HOST wst-8CC0125YW4 IN INVENTORY wst GROUP dev
  FOUND   88 FACTS FOR HOST wst-8CC0131NKL IN INVENTORY wst GROUP dev
  FOUND    6 HTML HOSTS IN /var/www/html/wst/dev

\`\`\`

EOF
exit 0
}

function die()
{
  echo >&2 "$1"
  exit 1
}

function columns()
{

COLS="$(cat << EOF
1 name
1 groups
0 cust
0 dtap
0 comment
0 ext_id
1 fqdn
1 main_ip
0 all_ipv4
0 all_ipv6
1 os
1 kernel
1 arch
0 virt
1 cpu_type
1 vcpus
1 ram
1 mem_usage
1 swap_usage
1 disk_usage
0 physdisk_size
1 nr_of_ifaces
1 timestamp
1 prodname
0 prodserial
EOF
)"

echo "$COLS"
}

function cols_exclude()
{
  grep -E '^0' "$COLS_CONFIG" \
    | cut -d' ' -f2 \
    | tr '\n' ',' \
    | sed 's/,$//g'
}

function group_list_all()
{

awx-cli group list -i "$INVENTORY" -a \
  | awk '/^[0-9]+/ {print $2}'        \
  | grep -Eo "$REGEX_GROUP"           \
  | sort -u

}

function group_get_id()
{

  [[ -z "$1" ]] && return
  [[ -z "$2" ]] && return

  awx-cli group get -i "$1" -n "$2" -f id
}

function hosts_by_group()
{

  [[ -z "$1" ]] && return
  [[ -z "$2" ]] && return

  awx-cli host list -i "$1" --group "$2" -f human -a \
    | awk '/^[0-9]+/ {print $2}'                     \
    | grep -E "$REGEX_HOST"                          \
    | sort

}

function host_get_facts()
{

  [[ -z "$1" ]] && return
  [[ -z "$2" ]] && return

  awx-cli host list_facts -i "$1" -n "$2" -f json > "$TMP" \
    && jq --argjson ansible_facts "$(<"$TMP")" '.+= {$ansible_facts}' <<< '{}'
}

function facts_get_total()
{
  local TOTAL_FACTS

  [[ -z "$1" ]] && return

  TOTAL_FACTS="$(jq -r '.ansible_facts | length' "$1" 2>/dev/null | head -1)"
  TOTAL_FACTS="${TOTAL_FACTS%% *}"

  echo "$TOTAL_FACTS"
}

function group_get_description()
{

  [[ -z "$1" ]] && return
  [[ -z "$2" ]] && return

  awx-cli group get -i "$1" -n "$2" -f json | jq -r .description
}

function facts2list()
{

while read -r GROUP _
do

  facts2group "$INVENTORY" "$GROUP"

done < "$INVENTORY_GROUPS"

}

function facts2head()
{
  local INVENTORY GROUP DESCRIPTION

HTML_HEAD="$(cat << EOF
<html>
<head>
    <meta charset="UTF-8">
    <title>$CMDB_TITLE</title>
    <style type="text/css">
      /* reset.css */
      html, body, div, span, applet, object, iframe,
      h1, h2, h3, h4, h5, h6, p, blockquote, pre,
      a, abbr, acronym, address, big, cite, code,
      del, dfn, em, img, ins, kbd, q, s, samp,
      small, strike, strong, sub, sup, tt, var,
      b, u, i, center,
      dl, dt, dd, ol, ul, li,
      fieldset, form, label, legend,
      table, caption, tbody, tfoot, thead, tr, th, td,
      article, aside, canvas, details, embed,
      figure, figcaption, footer, header, hgroup,
      menu, nav, output, ruby, section, summary,
      time, mark, audio, video {
        margin: 0; padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline;
      }
      /* HTML5 display-role reset for older browsers */
      article, aside, details, figcaption, figure,
      footer, header, hgroup, menu, nav, section { display: block; }
      body { line-height: 1; }
      ol, ul { list-style: none; }
      blockquote, q { quotes: none; }
      blockquote:before, blockquote:after,
      q:before, q:after { content: ''; content: none; }
      table { border-collapse: collapse; border-spacing: 0; }

      /* ansible-cmdb */
      *, body { font-family: sans-serif; font-weight: lighter; }
      a { text-decoration: none; }
      b { font-weight: bold; }
      p { margin-bottom: 1em; }

      header { position: fixed; top: 0px; left: 0px; right: 0px; background-color: #5e584c; overflow: auto; color: #E0E0E0; padding: 15px; z-index: 1000; }
      header h1 { font-size: x-large; float: left; line-height: 32px; font-weight: bold; }
      header #clear_settings { float: right; line-height: 32px; font-size: small; margin-left: 12px; }
      header #clear_settings a { color: #FFFFFF; font-weight: bold; padding: 6px; background-color: #0090F0; box-shadow: 2px 2px 0px 0px rgba(0,0,0,0.15); }
      header #generated { float: right; line-height: 32px; font-size: small; }
      header #top { display: none; }
      header #top a { line-height: 32px; margin-left: 64px; color: #FFFFFF; border-bottom: 1px solid #909090; }
      header #generated .detail { font-weight: bold; }

      footer { display: block; position: fixed; bottom: 0px; right: 0px; left: 0px; background-color: #d5d5d5; overflow: auto; color: #505050; padding: 4px; font-size: x-small; text-align: right; padding-right: 8px; }
      footer a { font-weight: bold; text-decoration: none; color: #202020; }

      #col_toggles { margin: 32px; margin-top: 100px; }
      #col_toggles h2 { display: block; font-size: 1.4em; margin-bottom: 32px; color: #606060; }
      #col_toggle_buttons { margin-left: 32px; font-weight: normal; line-height: 40px; }
      #col_toggles a { line-height: 40px; }
      #col_toggles a { display: inline-block; background-color: #009688; line-height: 32px; padding: 0px 15px 0px 15px; margin-right: 6px; box-shadow: 2px 2px 0px 0px rgba(0,0,0,0.35); color: #FFFFFF; }
      #col_toggles a.col-invisible { background-color: #B0B0B0; box-shadow: 0 0px 0px 0; }

      #host_overview { margin: 32px; }
      #host_overview h2 { display: block; font-size: 1.4em; color: #606060; }
      #host_overview_tbl_wrapper{ margin-left: 16px; }
      #host_overview table { width: 100%; clear: both; }
      #host_overview tr { border-bottom: 1px solid #F0F0F0; }
      #host_overview tr:hover { background-color: #F0F0F0; }
      #host_overview thead th { text-align: left; color: #707070; padding: 16px 0px 8px 16px; border-bottom: 1px solid #C0C0C0; font-weight: bold; cursor: pointer; background-repeat: no-repeat; background-position: center right; background-image: url("../static/images/sort_both.png"); }
      #host_overview thead th.sorting_desc { background-image: url("../static/images/sort_desc.png"); }
      #host_overview thead th.sorting_asc { background-image: url("../static/images/sort_asc.png"); }
      #host_overview tbody td { color: #000000; padding: 8px 12px 8px 12px; }
      #host_overview tbody a { text-decoration: none; color: #005c9d; }
      #host_overview_tbl_filter { float: right; color: #808080; padding-bottom: 32px; }
      #host_overview_tbl_filter label input { margin-left: 12px; }
      #host_overview_tbl_filter #filter_link a { color: #000000; background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAoUlEQVR4Xu2TIQ6EMBBF/+4dOUBFBYoboBHoBsuRUCgcnpDg3/Y7ICQVK3ebvPxJ30xH9QXom/PO/PoDAjSOY8pwIwFFr2EYUobjONj33bjGd3Ylr77v2bYNp7Hwhifs3HOeUdu2LMuCE1DXdedtl612cJ1R0zRM04TT1HVNjPERO/ecZxRCSBnmeWZdV+Ma39mVvABVVZUy3EhA0f//gvQB4y08WIiD/goAAAAASUVORK5CYII=) no-repeat left center; padding: 5px 0 5px 25px; }
      #host_overview_tbl_info { margin-top: 16px; color: #C0C0C0; }
      #host_overview .bar { clear: both; margin-bottom: 1px; }
      #host_overview .prog_bar_full { float: left; display: block; height: 12px; border: 1px solid #000000; padding: 1px; margin-right: 4px; color: white; text-align: center; }
      #host_overview .prog_bar_used { display: block; height: 12px; background-color: #8F4040; }
      #host_overview tbody td.error a { color: #FF0000; }
      #host_overview span.usage_detail { color: #606060; }
      #host_overview .error { color: #FF0000; }

      #hosts { margin-left: 32px; margin-bottom: 120px; }
      #hosts .toggle-collapse { cursor: pointer; }
      #hosts a.toggle-all { margin-top: 20px; display: inline-block; color: #0080FF; }
      #hosts a { color: #005c9d; }
      #hosts p.desc { color: #303030; margin-bottom: 32px; max-width: 800px; }
      #hosts h3.collapsed::before { color: #505050; margin-right: 16px; content: "⊞";  font-weight: 200; font-size: large; }
      #hosts h3.uncollapsed::before { color: #505050; margin-right: 16px; content: "⊟";  font-weight: 200; font-size: large;}
      #hosts h4.collapsed::before { color: #505050; margin-right: 16px; content: "⊞";  font-weight: 200; font-size: large;}
      #hosts h4.uncollapsed::before { color: #505050; margin-right: 16px; content: "⊟"; font-weight: 200; font-size: large;}
      #hosts h5.collapsed::before { color: #505050; margin-right: 16px; content: "⊞";  font-weight: 200; font-size: large;}
      #hosts h5.uncollapsed::before { color: #505050; margin-right: 16px; content: "⊟"; font-weight: 200; font-size: large;}
      #hosts div.collapsable { margin-left: 16px; }
      #hosts div.collapsed { display: none; }
      #hosts h3.uncollapsed { line-height: 1.5em; font-size: xx-large; border-bottom: 1px solid #D0D0D0; }
      #hosts h3.collapsed {  line-height: 1.5em; font-size: xx-large; }
      #hosts h4 { font-size: large; font-weight: bold; color: #404040; margin-top: 32px; margin-bottom: 32px; }
      #hosts h5 { font-weight: bold; color: #404040; margin-top: 32px; margin-bottom: 32px; }
      #hosts th { text-align: left; color: #808080; padding-bottom: 10px; }
      #hosts td { padding-left: 16px; color: #303030; padding-bottom: 10px; }
      #hosts ul { list-style: square; margin-left: 48px; }
      #hosts table.net_overview td, #hosts table.net_overview th { text-align: left; padding: 0px 0px 8px 16px; margin: 0px; }
      #hosts table.net_overview { margin: 16px 0px 16px 0px; }
      #hosts .error { color: #FF0000; }
    </style>
  </head>
  <body>

  <header>
    <h1>$CMDB_TITLE</h1>
    <span id="top"><a href="#">Back to top</a></span>
  </header>

  <div id="col_toggles">
    <div id="col_toggle_buttons"></div>
  </div>

  <div id="host_overview">
    <div id="host_overview_tbl_wrapper">
      <table id="host_overview_tbl" class="demo display dataTable compact">
      <thead>
        <tr>
            <th>$CMDB_GROUP_LABEL</th>
            <th>$CMDB_GROUP_DESC</th>
        </tr>
      </thead>
EOF
)"

echo "$HTML_HEAD"

}

function facts2foot()
{

HTML_FOOT="$(cat << EOF
    </table>
  </div>
</div>
</body>

</html>
EOF
)"

echo "$HTML_FOOT"

}

function facts2group()
{
  local INVENTORY GROUP DESCRIPTION

  INVENTORY="$1"
  GROUP="$2"
  DESCRIPTION="$(group_get_description "$INVENTORY" "$GROUP")"

  printf "<tr>\\n"
  printf "<td><a href=\"../%s/%s/index.html\">%s</a></td>\\n" \
         "$INVENTORY"                                      \
         "$GROUP"                                          \
         "$GROUP"
  printf "<td><a href=\"../%s/%s/index.html\">%s</a></td>\\n" \
         "$INVENTORY"                                      \
         "$GROUP"                                          \
         "$DESCRIPTION"
  printf "</tr>\\n"

}

function facts2cmdb()
{
  local INVENTORY GROUP TOTAL HOSTS FACTS

  [[ -z "$1" ]] && return
  [[ -z "$2" ]] && return

  INVENTORY="$1"
  GROUP="$2"
  HOSTS="$DIR/hosts/$INVENTORY/hosts-$GROUP"
  FACTS="$DIR/facts/$INVENTORY/$GROUP"
  DEST="$DIR/$INVENTORY/$GROUP"
  LINK_TARGET="../static"
  LINK_DIR="$DIR/$INVENTORY/static"
  mkdir -p "$FACTS"
  mkdir -p "$DEST"

  [[ -L "$LINK_DIR" ]] || ln -s "$LINK_TARGET" "$LINK_DIR"

  ansible-cmdb                     \
    --exclude-cols "$COLS_EXCLUDE" \
    -t html_fancy_split            \
    -p local_js=1,collapsed=1      \
    -i "$HOSTS" "$FACTS"           \
    && mv -f cmdb/* "$DEST/"

  TOTAL="$(find "$DEST" -type f -iname '*.html' | grep -cv index)"
  printf "FOUND %4d HTML HOSTS IN %s\\n" "$TOTAL" "$DEST"
}

group_get_all()
{

group_list_all > "$INVENTORY_GROUPS"

TOTAL_GROUPS="$(wc -l "$INVENTORY_GROUPS")"
TOTAL_GROUPS="${TOTAL_GROUPS%% *}"

[[ "$TOTAL_GROUPS" -eq 0 ]] \
  && die "NOT FOUND GROUPS IN INVENTORY $INVENTORY"

printf "FOUND %4d GROUPS IN INVENTORY %s MATCH WITH REGEX %s\\n" \
  "$TOTAL_GROUPS"                                                \
  "$INVENTORY"                                                   \
  "$REGEX_GROUP"

[[ "$SHOW_GROUP_ALL" -eq 1 ]] && cat "$INVENTORY_GROUPS"

}

function host_group_facts()
{

  INVENTORY="$1"
  HOST="$2"
  FACTS="$DIR/facts/$INVENTORY/$GROUP/$HOST"

  mkdir -p "$DIR/facts/$INVENTORY/$GROUP"

  host_get_facts "$INVENTORY" "$HOST" > "$FACTS"
  TOTAL_FACTS="$(facts_get_total "$FACTS")"
  printf "FOUND %4d FACTS FOR HOST %s IN INVENTORY %s GROUP %s\\n" \
    "$TOTAL_FACTS"                                                 \
    "$HOST"                                                        \
    "$INVENTORY"                                                   \
    "$GROUP"

  [[ "$TOTAL_FACTS" -eq 0 ]] && rm -f "$FACTS"
}

function facts2index()
{

  [[ "$INDEX_UPDATE" -eq 0 ]] && return

  echo "GENERATE INDEX ..."

  facts2head "$INVENTORY" >  "$INDEX"
  facts2list "$INVENTORY" >> "$INDEX"
  facts2foot "$INVENTORY" >> "$INDEX"

  wc -l "$INDEX"

}

function clean()
{
  rm -f "$INVENTORY_GROUPS" "$TMP"
}

function dependencies()
{

for DEP in ansible-cmdb jq
do

  if ! command -v "$DEP" >/dev/null 2>/dev/null
  then
    die "NOT FOUND $DEP TRY pip install $DEP"
  fi

done

}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

dependencies

[[ -n "$DIR"                  ]] || DIR='/var/www/html'
[[ -d "$DIR"                  ]] || die "NOT FOUND DIRECTORY $DIR"
[[ -n "$INVENTORY"            ]] || INVENTORY="$1"
[[ -z "$INVENTORY"            ]] && die "EMPTY INVENTORY"
[[ -n "$REGEX_GROUP"          ]] || REGEX_GROUP='.*'
[[ -z "$2"                    ]] || REGEX_GROUP="$2"
[[ -n "$REGEX_HOST"           ]] || REGEX_HOST='.*'
[[ -z "$3"                    ]] || REGEX_HOST="$3"
[[ -n "$COLS_CONFIG"          ]] || COLS_CONFIG="$DIR/columns"
[[ -e "$COLS_CONFIG"          ]] || columns > "$COLS_CONFIG"
[[ -n "$COLS_EXCLUDE"         ]] || COLS_EXCLUDE="$(cols_exclude)"
[[ -d "$DIR/hosts/$INVENTORY" ]] || mkdir -p "$DIR/hosts/$INVENTORY"
[[ -d "$DIR/facts/$INVENTORY" ]] || mkdir -p "$DIR/facts/$INVENTORY"
[[ -d "$DIR/$INVENTORY"       ]] || mkdir -p "$DIR/$INVENTORY"
[[ -n "$INDEX"                ]] || INDEX="$DIR/$INVENTORY/index.html"
[[ -n "$INDEX_UPDATE"         ]] || INDEX_UPDATE=1
[[ -n "$INDEX_ONLY"           ]] || INDEX_ONLY=0
[[ -n "$CMDB_TITLE"           ]] || CMDB_TITLE='CMDB'
[[ -n "$CMDB_GROUP_LABEL"     ]] || CMDB_GROUP_LABEL='group'
[[ -n "$CMDB_GROUP_DESC"      ]] || CMDB_GROUP_DESC='description'
[[ -n "$SHOW_GROUP_ALL"       ]] || SHOW_GROUP_ALL='0'

TMP="$(mktemp)"
INVENTORY_GROUPS="$(mktemp)"

group_get_all
facts2index

[[ "$INDEX_ONLY" -eq 1 ]] && exit 0

while read -r GROUP _
do

  GROUP_ID="$(group_get_id "$INVENTORY" "$GROUP")"
  [[ -z "$GROUP_ID" ]] && continue

  HOSTS="$DIR/hosts/$INVENTORY/hosts-$GROUP"
  hosts_by_group "$INVENTORY" "$GROUP_ID" > "$HOSTS"

  TOTAL_HOSTS="$(wc -l "$HOSTS")"
  TOTAL_HOSTS="${TOTAL_HOSTS%% *}"
  printf "FOUND %4d HOSTS IN INVENTORY %s MATCH WITH GROUP %s\\n" \
    "$TOTAL_HOSTS"                                                \
    "$INVENTORY"                                                  \
    "$GROUP"

  while read -r HOST _
  do

    host_group_facts "$INVENTORY" "$HOST" "$FACTS"

  done < "$HOSTS"

  # INSERT [GROUP] IN HOSTS
  sed -i "1 i [$GROUP]" "$HOSTS"

  facts2cmdb "$INVENTORY" "$GROUP"

done < "$INVENTORY_GROUPS"

clean
