#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN INVENTORY_SOURCE [KEY|all]

\`\`\`

Get variable from _inventory_source_.

\`\`\`bash

  $BIN inventory_pve source_path
  hosts-pve

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -n "$KEY" ]] && KEY='all'
[[ -z "$1"   ]] && die "EMPTY INVENTORY_SOURCE"
[[ -z "$2"   ]] || KEY="$2"

INVENTORY_SOURCE="$1"

JSON="$(mktemp --suffix .json)"

awx-cli inventory_source get  \
  --format json               \
  --name "$INVENTORY_SOURCE"  > "$JSON" 2>/dev/null

[[  -s "$JSON" ]] || die "EMPTY JSON $JSON"

JQ='.'
[[ "$KEY" != 'all' ]] && JQ=".$KEY"

jq -r "$JQ" "$JSON" | grep -vi null

rm -f "$JSON"
