#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

  $BIN [INVENTORY] [LIMIT] [MODULE_ARGS]

Execute commands usinn shell module in ad-hoc of AWX

Example:

  $BIN pve dev uptime

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY INVENTORY"
INVENTORY="$1"

[[ -z "$2" ]] && die "EMPTY LIMIT"
LIMIT="$2"

[[ -z "$3" ]] && die "EMPTY MODULE_ARGS"
MODULE_ARGS="$3"

BECOME='true'
JOB_TYPE='run'
MODULE_NAME='shell'
VERBOSE='more_verbose'

awx-cli ad_hoc launch                         \
  --job-type        "$JOB_TYPE"               \
  --inventory       "$INVENTORY"              \
  --limit           "$LIMIT"                  \
  --credential      "$DEFAULT_SSH_CREDENTIAL" \
  --module-name     "$MODULE_NAME"            \
  --module-args     "$MODULE_ARGS"            \
  --verbosity       "$VERBOSE"                \
  --become-enabled  "$BECOME"                 \
  --monitor
