#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:
  $BIN

Description

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die "EMPTY PROJECT"

PROJECT="$1"

JSON=$(mktemp --suffix .json)

awx-cli project get \
  --name "$PROJECT" \
  --format json     > "$JSON" 2>/dev/null

[[ -s "$JSON" ]] || die "EMPTY JSON"

JQ='.summary_fields.last_job.id'
ID="$(jq -r "$JQ" "$JSON")"
echo "$ID"

rm -f "$JSON"
