#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

RED="$(tput setaf 196)"
GREEN="$(tput setaf 46)"
DIR_REAL="$(realpath "$DIR_BIN")"
DIR_BASE="$(dirname "$DIR_REAL")"
AWX_CONFIG="$HOME/.awx-config"

die ()
{
  printf "%s\n" "${RED}[ERROR] $1 $NORMAL" && exit 1
}

log ()
{
  printf "%s\n" "${NORMAL}[INFO] $1 $NORMAL"
}

success ()
{
  printf "%s\n" "${GREEN}[OK] $1 $NORMAL" && exit 1
}

[[ ! -e "$AWX_CONFIG" ]] && die "NOT FOUND FILE: $AWX_CONFIG"

eval $(sed '/:/!d;/^ *#/d;s/:/ /;' < "$AWX_CONFIG" | while read -r k v
do
    str="$k='$v'"
    echo "$str"
done)

get_file_list()
{

  [[ -z "$1" ]] && exit 1

  find . -type f -iname "$1" | cut -c 3- | while read -r FILE
  do
    echo "$FILE"
  done

}

filelist_projects()
{

  get_file_list 'ansible*.json'

}

filelist_job_templates()
{

  get_file_list 'job_template*.json'

}

filelist_workflows()
{

  get_file_list 'workflow*.json'

}

grant_project()
{
  awx-cli role grant \
    -v               \
    --type use       \
    --team "$2"      \
    --project "$1"
}

grant_job_template()
{
  awx-cli role grant \
    -v               \
    --type execute   \
    --team "$2"      \
    --job-template "$1"
}

grant_workflow()
{
  awx-cli role grant \
    -v               \
    --type execute   \
    --team "$2"      \
    --workflow "$1"
}

group_get_id()
{
  awx-cli group get  \
    --inventory "$1" \
    --name "$2"      \
    --format id
}

host_get_id()
{
  awx-cli host get   \
    --inventory "$1" \
    --name "$2"      \
    --format id
}

host_associate()
{
  awx-cli host associate \
    --host "$1"          \
    --group "$2"
}
