#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2086

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN JOB_TEMPLATE PROJECT_NAME PLAYBOOK_FILE [EXTRA_VARS_YAML]

\`\`\`

Create _job template_ and associate default credentials in _AWX_.

\`\`\`bash

  $BIN wst_wol_v0.1.0 ansible_wst_v0.1.0 wst-wol.yml wst_extra_vars.yml

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY JOB_TEMPLATE NAME"
[[ -z "$2" ]] && die "EMPTY PROJECT NAME"
[[ -z "$3" ]] && die "EMPTY PLAYBOOK FILE"

NAME="$1"
PROJECT="$2"
PLAYBOOK="$3"
VARIABLES=''

[[ -e "$4" ]] && VARIABLES="--extra-vars @$4"

echo "CREATE JOB_TEMPLATE $NAME"
awx-cli job_template create       \
  --name "$NAME"                  \
  --job-type run                  \
  --project "$PROJECT"            \
  --playbook "$PLAYBOOK"          \
  --verbosity more_verbose        \
  --ask-inventory-on-launch true  \
  --ask-limit-on-launch true $VARIABLES $AWX_DEBUG

if [[ -n "$DEFAULT_SSH_CREDENTIAL" ]]
then

echo "ASSOCIATE CREDENTIAL $DEFAULT_SSH_CREDENTIAL TO A JOB_TEMPLATE"
awx-cli job_template associate_credential \
  --job-template "$NAME"                  \
  --credential "$DEFAULT_SSH_CREDENTIAL" $AWX_DEBUG

fi

if [[ -n "$DEFAULT_VAULT_CREDENTIAL" ]]
then

echo "ASSOCIATE CREDENTIAL $DEFAULT_VAULT_CREDENTIAL TO A JOB_TEMPLATE"
awx-cli job_template associate_credential \
  --job-template "$NAME"                  \
  --credential "$DEFAULT_VAULT_CREDENTIAL" $AWX_DEBUG

fi
