#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN CSV

\`\`\`

Associate _user_ to _team_ specified in \`.csv\` file.

Example:

\`\`\`bash

  $BIN awx-users.csv

\`\`\`bash

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY CSV"
[[ -e "$1" ]] || die "NOT FOUND $1"

CSV="$1"

while read -r USERNAME TEAM
do

  ID="$(awx-cli user get -f id "$USERNAME")"

  if [[ -z "$ID"   ]]
  then
    stderror "SKIP USER $USERNAME NOT FOUND"
    continue
  fi

  if [[ -z "$TEAM" ]]
  then
    stderror "SKIP USER $USERNAME EMPTY TEAM"
    continue
  fi

  awx-team-associate "$USERNAME" "$TEAM"

done < "$CSV"
