#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF

Usage:

\`\`\`bash

  $BIN INVENTORY GROUP_ID

\`\`\`

Get enabled hosts in group of inventory.

Example:

\`\`\`bash

  $BIN wst 123

	150 wstdev01
	151 wstdev02
	152 wstdev03
	153 wstdev04

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY INVENTORY"
[[ -z "$2" ]] && die "EMPTY GROUP_ID"

INVENTORY="$1"
GROUP_ID="$2"

awx-cli host list          \
  --all-pages              \
  --inventory "$INVENTORY" \
  --group     "$GROUP_ID"  | awk '/true/ {print $1, $2}'
