#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF

Usage:

\`\`\`bash

  $BIN INVENTORY GROUP

\`\`\`

Compare and merge AWX group variables with local YAML group file.

Example:

\`\`\`bash

  $BIN wst dev

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY INVENTORY"
[[ -z "$2" ]] && die "EMPTY GROUP"

INVENTORY="$1"
GROUP="$2"

SRC_YML="group_vars/${GROUP}.yml"
BAK_YML="group_vars/${GROUP}-$(date +%s).yml"
SRD_YML="$(mktemp --suffix .yml)"
AWX_YML="$(mktemp --suffix .yml)"
MRG_YML="$(mktemp --suffix .yml)"

[[ -e "$SRC_YML" ]] || die "NOT FOUND $SRC_YML"

cp -f "$SRC_YML" "$BAK_YML"

awx-group-get-variable "$INVENTORY" "$GROUP" > "$AWX_YML"
yq -y --sort-keys -r . "$SRC_YML"            > "$SRD_YML"

TOT_SRD="$(wc -l "$SRD_YML" | awk '{print $1}')"
TOT_AWX="$(wc -l "$AWX_YML" | awk '{print $1}')"
TOT_DFF="$((TOT_SRD+TOT_AWX))"

diff -U "$TOT_DFF" "$SRD_YML" "$AWX_YML" \
  | sed 's/^+//g'                        \
  | sed 's/^-//g'                        \
  | grep -v '@@'                         \
  | tail -n+3                            \
  | sed 's/^--$/---\n\n/g'               \
  | sed 's/^ \([a-z]\+\)/\1/g'           > "$SRC_YML" && echo "$SRC_YML"

rm -f "$SRD_YML"
rm -f "$AWX_YML"
rm -f "$MRG_YML"
