#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

Description

\`\`\`bash

  $BIN

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die "EMPTY HOST"

HOST="$1"
PREFIX="${HOST//-*/}"
INVENTORY="${PREFIX,,}"

[[ -z "$2" ]] || INVENTORY="$2"

[[ -z "$INVENTORY" ]] && die "EMPTY INVENTORY"

JSON="$(mktemp --suffix .json)"

awx-cli host get           \
  --inventory "$INVENTORY" \
  --name "$HOST"           \
  --format json > "$JSON" 2>/dev/null

[[ -s "$JSON" ]] || die "EMPTY JSON"

DESCRIPTION="$(jq -r '.description' "$JSON")"

jq -r '.summary_fields.recent_jobs' "$JSON" \
  | jq -r '.[] | "\(.id) \(.finished) \(.status) \(.name)"' \
  | while read -r ID D STATUS NAME
    do
      DATE="$(date -d "$D" +%F\ %T)"
      printf "%s %s %s %s %11s %s\\n" \
        "$HOST" "$DESCRIPTION" "$ID" "$DATE" "$STATUS" "$NAME"
    done

rm -f "$JSON"
