#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2023 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2023 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1091

[[ -n "$BASH_DEBUG" ]] && set -x

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`

  $BIN JOB_TEMPLATE

\`\`\`

Get the _ID_ of the last run of a _job_template_.

Example:

\`\`\`

  $BIN wst_adm_v1.5.0

    180922

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -n "$JOB_TEMPLATE"   ]] || JOB_TEMPLATE="$1"
[[ -z "$1"              ]] || JOB_TEMPLATE="$1"
[[ -z "$JOB_TEMPLATE"   ]] && die "UNDEFINED JOB_TEMPLATE"
[[ -n "$PAGE_SIZE"      ]] || PAGE_SIZE='20'
[[ -n "$PAGE"           ]] || PAGE='1'

awx-cli job list                 \
  --job-template "$JOB_TEMPLATE" \
  --format id                    \
  --page "$PAGE"                 \
  --page-size "$PAGE_SIZE"       \
  | tr ' ' '\n'                  \
  | sort -nr                     \
  | head -1
