#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:
  $BIN

Description

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die "EMPTY INVENTORY"
[[ -z "$2" ]] && die "EMPTY VARIABLE"
[[ -z "$3" ]] && die "EMPTY NEW_VALUE"

INVENTORY="$1"
VARIABLE="$2"
NEW_VALUE="$3"

JSON=$(mktemp --suffix .json)

awx-cli inventory get \
  --format json       \
  --name "$INVENTORY" > "$JSON" 2>/dev/null

[[ -s "$JSON" ]] || die "EMPTY JSON"

YAML=$(mktemp --suffix .yml)

jq -r .variables "$JSON" > "$YAML" 2>/dev/null

VALUE="$(yq -r ".$VARIABLE" "$YAML" | grep -vi null)"

title2 "MODIFY $VARIABLE WITH $NEW_VALUE IN $INVENTORY INVENTORY"

code
if [[ "$VALUE" = "$NEW_VALUE" ]]
then
  echo "ALREADY SET $VARIABLE = $NEW_VALUE"
else

  jq_yq_modify "$YAML" "$VARIABLE" "$NEW_VALUE"

  [[ -s "$YAML" ]] || die "EMPTY YAML"

  awx-cli inventory modify   \
    --name      "$INVENTORY" \
    --variables "@$YAML"

fi
code

rm -f "$JSON"
rm -f "$YAML"
