#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2059
# shellcheck disable=SC2086

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

$(code)

  $BIN INVENTORY REGEXP GROUP

$(code)

Associate _host_ to _group_ based on variables in \`host_vars\`
directory.

Example:

$(code)

  $BIN pve REGEXP dev

$(code)
EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die 'EMPTY INVENTORY'
INVENTORY="$1"
HOST_PREFIX="${1//-.*}"

[[ -z "$HOST_PREFIX" ]] && die 'EMPTY HOST_PREFIX'

[[ -z "$2" ]] && die 'EMPTY REGEXP'
REGEXP="$2"

[[ -z "$3" ]] && die 'EMPTY GROUP NAME'
GROUP="$3"

[[ ! -d 'host_vars' ]] && die 'NOT FOUND host_vars DIRECTORY'

GROUP_ID=$(group_get_id "$INVENTORY" "$GROUP")

[[ -z "$GROUP_ID" ]] && die "NOT FOUND GROUP_ID FOR GROUP $GROUP"

grep -l "$REGEXP" host_vars/${HOST_PREFIX}-*.yml | while read -r FILE
do
  HOST="$(basename "$FILE" | cut -d. -f1)"
  HOST_ID="$(host_get_id "$INVENTORY" "$HOST")"
  [[ -z "$HOST_ID" ]] && die "NOT FOUND HOST_ID FOR HOST $HOST"

  MSG='ASSOCIATE HOST %s TO GROUP %s IN INVENTORY %s'
  LOG="$(printf "$MSG" "$HOST" "$GROUP" "$INVENTORY")"
  log "$LOG"
  host_associate "$HOST_ID" "$GROUP_ID"
done
