#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

HOST_IDS="$(mktemp)"

function inventory_get_id()
{
  awx-cli inventory get \
    --format id         \
    --name "$1"
}

function disable_host()
{
  awx-cli host modify   \
    --enabled false     \
    --inventory "$1"    \
    --format human "$2"
    #| awk '/false/{print "$1,$2"}'
}

[[ -z "$1" ]] && die "EMPTY INVENTORY"
INVENTORY="$1"
INVENTORY_ID="$(inventory_get_id "$INVENTORY")"

awx-cli host list             \
  --inventory "$INVENTORY_ID" \
  --enabled true              \
  --all-pages                 \
  --format id | tr ' ' '\n'   > "$HOST_IDS"

while read -r HOST_ID
do
  disable_host "$INVENTORY_ID" "$HOST_ID"
done < "$HOST_IDS"
