#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN JOB_NAME [JOB_LIMIT]

\`\`\`

Launch job template with limit.

Example:

\`\`\`bash

  $BIN wst_wlp_v1.0.0 dev

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -n "$JOB_NAME"   ]] || JOB_NAME="$1"
[[ -z "$JOB_NAME"   ]] && die "EMPTY JOB_NAME"
[[ -n "$JOB_LIMIT"  ]] || JOB_LIMIT="$2"
[[ -z "$JOB_LIMIT"  ]] && JOB_LIMIT="$DEFAULT_LIMIT"
[[ -z "$JOB_LIMIT"  ]] && die "EMPTY JOB_LIMIT"
[[ -n "$EXTRA_VARS" ]] || EXTRA_VARS="$3"

if [[ -z "$EXTRA_VARS" ]]
then

  awx-cli job launch -J "$JOB_NAME" --monitor --limit "$JOB_LIMIT" >&2

else

  [[ -f "$EXTRA_VARS" ]] || die "NOT FOUND FILE $EXTRA_VARS"
  [[ -s "$EXTRA_VARS" ]] || die "EMPTY FILE $EXTRA_VARS"

  stderror "FOUND EXTRA VARS IN $EXTRA_VARS FOR $JOB_NAME"
  yq -yr '.' "$EXTRA_VARS"

  awx-cli job launch            \
    --job-template "$JOB_NAME"  \
    --monitor                   \
    --extra-vars "@$EXTRA_VARS" \
    --limit "$JOB_LIMIT" >&2

fi
