#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ -z "$1" ]] && exit 1
INVENTORY="$1"

[[ -z "$2" ]] && exit 1
LIMIT="$2"

[[ -z "$3" ]] && exit 1
MODULE_ARGS="$3"

CFG="$HOME/.tower_cli.cfg"
BECOME='true'
CREDENTIAL="$(grep 'credential=' "$CFG" | cut -d= -f2)"
CREDENTIAL='ssh_f0664_ansible'
JOB_TYPE='run'
MODULE_NAME='shell'
VERBOSE='more_verbose'

awx-cli ad_hoc launch              \
  --job-type        "$JOB_TYPE"    \
  --inventory       "$INVENTORY"   \
  --limit           "$LIMIT"       \
  --credential      "$CREDENTIAL"  \
  --module-name     "$MODULE_NAME" \
  --module-args     "$MODULE_ARGS" \
  --verbosity       "$VERBOSE"     \
  --become-enabled  "$BECOME"      \
  --monitor
