#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN JSON VERBOSITY

\`\`\`

Modify verbosity in \`.json\` _file_.

\`\`\`bash

  $BIN pve_kvm.json 1

	BACKUP job_template/pve_kvm.json TO /tmp/tmp.YKCruLt5xb.json
    "verbosity": 2,                      |     "verbosity": 1,

\`\`\`
EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY JSON"
[[ -e "$1" ]] || die "NOT FOUND $1"
[[ -z "$2" ]] && die "EMPTY VERBOSITY"

JSON="$1"
VERBOSITY="$2"

BAK="$(mktemp --suffix .json)"
stderror "BACKUP $JSON TO $BAK"
cp -f "$JSON" "$BAK"

jq_modify_verbosity "$JSON" "$VERBOSITY"

diff -y --suppress-common-lines "$BAK" "$JSON"
