#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

[[ -z "$1" ]] && die "EMPTY JOB_TEMPLATE"

JOB_TEMPLATE="$1"

JSON=$(mktemp --suffix .json)

awx-cli job_template get   \
  --name "$JOB_TEMPLATE"   \
  --format json > "$JSON" 2>/dev/null

[[ -s "$JSON" ]] || die "EMPTY JSON"

LAST_JOB="$(jq -r '.related.last_job' "$JSON")"

ID="$(echo "$LAST_JOB" | grep -oE '/[0-9]+' | tr -d /)"

echo "$ID"

rm -f "$JSON"
