#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:
  $BIN

Description

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

JSON_LIST="$(mktemp)"

if [[ -z "$1" ]]
then
  filelist_workflows  >  "$JSON_LIST"
else
  #[[ ! -e "$1" ]] && die "NOT FOUND $1"
  echo "$1"           > "$JSON_LIST"
fi

awx_cfg_read

while read -r FILE
do
  NAME="$(basename "$FILE" .json)"
  ID="$(awx-cli workflow get -n "$NAME" -f id)"
  URL="$AWX_CFG_HOST/#/templates/workflow_job_template/$ID"
  printf "%-30s %s\\n" "$NAME" "$URL"
done < "$JSON_LIST"

rm -f "$JSON_LIST"
