#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null
# shellcheck disable=SC2002

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF

Usage:

\`\`\`bash

  $BIN

\`\`\`

Add suffix to job_template with project and show diff

Example:

\`\`\`bash


  $BIN job_template/wst_wol_v0.1.0.json hotfix

	RENAME FROM job_template/wst_wol_v0.1.0.json TO job_template/wst_wol_v0.1.0-hotfix.json

			"name": "wst_wol_v0.1.0",             |         "name": "wst_wol_v0.1.0-hotfix",

	REPLACE ansible_wst_v1.0.0 WITH ansible_wst_v1.0.0-hotfix

	DIFF job_template/wst_wol_v0.1.0.json WITH job_template/wst_wol_v0.1.0-hotfix.json

			"name": "wst_wol_v0.1.0",                 |     "name": "wst_wol_v0.1.0-hotfix",
			"project": "ansible_wst_v1.0.0",          |     "project": "ansible_wst_v1.0.0-hotfix",


\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY JSON"
[[ -e "$1" ]] || die "NOT FOUND JSON $1"
[[ -z "$2" ]] && die "EMPTY SUFFIX"

JSON="$1"
SUFFIX="$2"

NAME="$(basename "$JSON" .json)"
NEW_NAME="$NAME-$SUFFIX"
DIR="$(dirname "$JSON")"
NEW_JSON="$DIR/$NAME-$SUFFIX.json"

awx-json-rename "$JSON" "$NEW_NAME"

[[ ! -e "$NEW_JSON" ]] && die "NOT FOUND $NEW_JSON"

PROJECT="$(json_get_project "$JSON")"
[[ -z "$PROJECT" ]] && die "EMPTY PROJECT"

echo "REPLACE $PROJECT WITH $PROJECT-$SUFFIX"
sed -i "s/$PROJECT/$PROJECT-$SUFFIX/g" "$NEW_JSON"

LEN="$(grep project "$NEW_JSON" | wc -c)"
WIDTH="$((LEN*2+10))"

echo
echo "DIFF $JSON WITH $NEW_JSON"
echo
diff -y --suppress-common-lines -W "$WIDTH" "$JSON" "$NEW_JSON"
