#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null
# shellcheck disable=SC1117
# shellcheck disable=SC2086

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\'\'\'bash

  $BIN JOB_TEMPLATE [TEAM]

\'\'\'

Show the permissions of a _job template_ for a _team_.
By default output is a CSV, you can enable Markdown output.

Example:

\'\'\'bash

  $BIN pve_upd_v0.1.0 devops

    job_template,pve_upd_v0.4.0,Execute,devops

  MD_TABLE=1 $BIN pve_upd_v0.4.0 devops

    | _job_template_       | \`pve_upd_v0.4.0                        \` | _Execute_  | _devops_             |

\'\'\'

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1"        ]] && die "EMPTY JOB_TEMPLATE"
JOB_TEMPLATE="$1"
[[ -z "$2"        ]] || TEAM="$2"
[[ -z "$TEAM"     ]] && TEAM="$DEFAULT_TEAM"
[[ -n "$MD_TABLE" ]] || MD_TABLE=0

RESOURCE_TYPE='job_template'
RESOURCE_NAME="$JOB_TEMPLATE"
ROLE_LIST_FUNC='role_list_team_csv'
[[ "$MD_TABLE" -eq 1 ]] && ROLE_LIST_FUNC='role_list_team_table'

role_list_team_job_template "$TEAM" "$JOB_TEMPLATE" | while read -r TYPE
do

  $ROLE_LIST_FUNC "$RESOURCE_TYPE" "$RESOURCE_NAME" "$TYPE" "$TEAM"

done
