#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2116,SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN ENVIRONMENT

\`\`\`

Overwrite \`~/.tower_cli.cfg\` with enviroment config using
\`~/.awx-config\` and \`pass\` command for retrieve passwords to use
with \`awx-cli\`.

First copy \`.awx-config-example\` to \`~/.awx-config\`, customize
variables according your enviroment.

Example:

\`\`\`bash

  $BIN DEVELOP

\`\`\`

Define enviroments in \`~/.awx-config\`:

\`\`\`

	DEVELOP: awx-dev
	DEVELOP_USER: admin
	DEVELOP_PASSWORD_STORE_DIR: ~/.password-store-awx-dev
	MASTER_PASSWORD_STORE_DIR: ~/.password-store-awx-prd
	MASTER: awx-prd
	MASTER_USER: admin
	PASS_PREFIX: awx/
	PASS_SUFFIX: /

\`\`\`

Generate or insert credentials in multiple \`pass\` repositories:

\`\`\`bash

  export PASSWORD_STORE_DIR=~/.password-store-awx-dev
	pass awx/awx-dev/host
	pass awx/awx-dev/admin_password

  export PASSWORD_STORE_DIR=~/.password-store-awx-prd
	pass awx/awx-prd/host
	pass awx/awx-prd/admin_password

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

if [[ -n "$ANSIBLE_PASS_PASSWORD_STORE_DIR" ]]
then
  export PASSWORD_STORE_DIR="$ANSIBLE_PASS_PASSWORD_STORE_DIR"
fi

[[ -z "$1" ]] && die "EMPTY ENVIROMENT"

ENV="${1^^}"
USR="${ENV}_USER"

if [[ ! -z "${ENV}_PASSWORD_STORE_DIR" ]]
then
  AWX_PASS_DIR="${ENV}_PASSWORD_STORE_DIR"
  export PASSWORD_STORE_DIR="${!AWX_PASS_DIR}"
fi

AWX_ENV="$(echo "${!ENV}")"
AWX_USER="$(echo "${!USR}")"
AWX_HOST=$(pass "${PASS_PREFIX}${AWX_ENV}${PASS_SUFFIX}host")
AWX_PASS=$(pass "${PASS_PREFIX}${AWX_ENV}${PASS_SUFFIX}${AWX_USER}_password")

[[ -z "$AWX_PASS" ]] && die "EMPTY AWX_PASS"

CONFIG=$(cat << EOF
host=$AWX_HOST
password=$AWX_PASS
username=$AWX_USER
verify_ssl=false
EOF
)

AWX_CFG="$HOME/.tower_cli.cfg"
echo "$CONFIG" > "$AWX_CFG" && chmod 600 "$AWX_CFG"

HTTP_CODE="$(curl -s -o /dev/null -w "%{http_code}" "$AWX_HOST")"

[[ "$HTTP_CODE" != '200' ]] && die "HTTP RESPONSE CODE != 200 $AWX_HOST"

SUPERUSER="$(awx-cli user get "$AWX_USER" -f json | jq '.is_superuser')"

if [[ "$AWX_USER" = 'true' ]]
then
  awx-setting-get-tower-url-base
  awx-setting-get-custom-login-info
fi

awx-cli version
