#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

$(code)bash

  $BIN HOST [INVENTORY]

$(code)

Enable _host_ in _inventory_.

Example:

  Implicit _inventory_ from _host_:

$(code)bash

  $BIN pve-dev01

$(code)

  Explicit _host_ and _inventory_:

$(code)bash

  $BIN dev01 pve

$(code)

Result:

$(code)

  === ========= ========= =======
  id    name    inventory enabled
  === ========= ========= =======
  123 pve-dev01         2    true
  === ========= ========= =======

$(code)

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY HOST"

HOST="$1"

[[ "$HOST" =~ [a-zA-Z]+-.* ]] && PREFIX="${HOST//-*/}"

if [[ -z "$PREFIX" ]]
then
  # input  : spve01.*
  # output : pve
  REGEX='[a-z]{3,4}'
  PREFIX="$(echo "$HOST" | grep -oE "$REGEX" | rev | cut -c -3 | rev)"
fi

INVENTORY="${PREFIX,,}"

[[ -z "$2" ]] || INVENTORY="$2"
[[ -z "$INVENTORY" ]] && die "EMPTY INVENTORY"

title2 "ENABLE $HOST IN $INVENTORY INVENTORY"
code
awx-cli host modify --enabled true -i "$INVENTORY" -n "$HOST" -v
code
