#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2023 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2023 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

Get all _groups_ from one _inventory_ and iterate each _group_ to get
all _hosts_ and generate CSV with basic attributes of each _host_.

  inventory_host,description,ansible_host,primary_macaddress,inventory_serial

Example:

\`\`\`bash

  $BIN

  'wst01dev01','imported','192.168.1.11','ca:fe:ca:fe:00:3d','S12345678'
  'wst01dev02','imported','192.168.1.12','fa:fa:fa:02:ac:dc','S12345679'

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

if ! command -v pv >/dev/null 2>/dev/null
then
  die "NOUT FOUND pv, TRY apt install pv"
fi

[[ -n "$BASH_DEBUG"       ]] && set -x
[[ -n "$INVENTORY_NAME"   ]] || INVENTORY_NAME="$1"
[[ -z "$INVENTORY_NAME"   ]] && die "UNDEFINED INVENTORY_NAME"
[[ -n "$INVENTORY_GROUPS" ]] || INVENTORY_GROUPS="${INVENTORY_NAME}-groups.log"
[[ -n "$INVENTORY_HOSTS"  ]] || INVENTORY_HOSTS="${INVENTORY_NAME}-hosts.log"
[[ -n "$INVENTORY_CSV"    ]] || INVENTORY_CSV="${INVENTORY_NAME}-hosts.csv"

COUNT_GROUPS="$(awx-group-count "$INVENTORY_NAME")"
stderror "COUNT $COUNT_GROUPS GROUPS IN $INVENTORY_NAME"
stderror "GET GROUPS FROM $INVENTORY_NAME"
awx-inventory-get-groups "$INVENTORY_NAME" \
  | pv -lw 40 -s "$COUNT_GROUPS" > "$INVENTORY_GROUPS"

TOTAL_GROUPS="$(wc -l "$INVENTORY_GROUPS")"
TOTAL_GROUPS="${TOTAL_GROUPS%% *}"
stderror "WRITE $TOTAL_GROUPS GROUPS IN $INVENTORY_GROUPS"

COUNT_HOSTS="$(awx-host-count "$INVENTORY_NAME")"
stderror "COUNT $COUNT_HOSTS HOSTS IN $INVENTORY_NAME"
stderror "GET HOSTS FROM $INVENTORY_NAME"

while read -r INVENTORY_GROUP
do

  awx-inventory-group-get-hosts "$INVENTORY_NAME" "$INVENTORY_GROUP"

done < "$INVENTORY_GROUPS" \
  | pv -lw 40 -s "$COUNT_HOSTS" > "$INVENTORY_HOSTS"

TOTAL_HOSTS="$(wc -l "$INVENTORY_HOSTS")"
TOTAL_HOSTS="${TOTAL_HOSTS%% *}"
stderror "WRITE $TOTAL_HOSTS HOSTS IN $INVENTORY_HOSTS"

stderror "GET HOSTS VARIABLES FROM $INVENTORY_NAME"
while read -r INVENTORY_HOST
do

  awx-host-get-csv "$INVENTORY_HOST" "$INVENTORY_NAME"

done < "$INVENTORY_HOSTS" \
  | pv -lw 40 -s "$TOTAL_HOSTS" > "$INVENTORY_CSV"

TOTAL_CSV="$(wc -l "$INVENTORY_CSV")"
TOTAL_CSV="${TOTAL_CSV%% *}"
stderror "WRITE $TOTAL_CSV RECORDS IN $INVENTORY_CSV"
