#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN GROUPS_FILE INVENTORY_JSON

\`\`\`

Get _hosts_ from _group_ file of _inventory_.

Example:

\`\`\`bash

  $BIN pvedeploy pve.json

    dev pve-dev-01
    prd pve-prd-01
    prd pve-prd-02

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY GROUPS_FILE"
GROUPS_FILE="$1"

[[ -e "$1" ]] || die "NOT FOUND GROUPS_FILE $GROUPS_FILE"

[[ -z "$2" ]] && die "EMPTY INVENTORY_JSON"
INVENTORY_JSON="$2"

[[ -e "$2" ]] || die "NOT FOUND INVENTORY_JSON $INVENTORY_JSON"

awk '{print $1}' "$GROUPS_FILE" | while read -r GROUP
do
  awx-json-inventory-group-get-hosts "$INVENTORY_JSON" "$GROUP" \
    | while read -r HOST
    do
      printf "%s %s\\n" "$GROUP" "$HOST"
    done
done
