#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

[[ -n "$BASH_DEBUG" ]] && set -x

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN JOB_TEMPLATE SCHEDULE_NAME

\`\`\`

Delete schedule to run _job_template_.

\`\`\`bash

  $BIN wst_wol_all_v0.1.0 'WoL all Workstations'
  DELETE SCHEDULE WoL all Workstations FOR wst_wol_all_v0.1.0 WITH ID 42

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1"             ]] || JOB_TEMPLATE="$1"
[[ -z "$2"             ]] || SCHEDULE_NAME="$2"
[[ -z "$JOB_TEMPLATE"  ]] && die "EMPTY JOB_TEMPLATE NAME"
[[ -z "$SCHEDULE_NAME" ]] && die "EMPTY SCHEDULE_NAME"

SCHEDULE_ID="$(awx-schedule-get-id "$JOB_TEMPLATE" "$SCHEDULE_NAME")"
MSG="SCHEDULE $SCHEDULE_NAME FOR $JOB_TEMPLATE"

if [[ -z "$SCHEDULE_ID" ]]
then
  stderror "NOTHING TO DO, NOT FOUND $MSG"
  exit 0
fi

stderror "DELETE $MSG WITH ID $SCHEDULE_ID"

awx-cli schedule delete          \
  --name "$SCHEDULE_NAME"        \
  --job-template "$JOB_TEMPLATE" || die "FAILED TO DELETE $MSG"
