#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2116,SC1090

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

Remove \`~/.tower_cli.cfg\` to prevent unauthorized access.

Example:

\`\`\`bash

  $BIN

\`\`\`

EOF

}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -e "$AWX_CFG" ]] || die "NOT FOUND FILE $AWX_CFG"

if command -v shred >/dev/null
then
  shred "$AWX_CFG"
fi

echo "DELETE $AWX_CFG"
rm -f "$AWX_CFG"
