#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

[[ -z "$1" ]] && die "EMPTY HOST"

HOST="$1"

[[ "$HOST" =~ [a-z]+-.* ]] && PREFIX="${HOST//-*/}"

if [[ -z "$PREFIX" ]]
then
  # input  : spve01.*
  # output : pve
  REGEX='[a-z]{3,4}'
  PREFIX="$(echo "$HOST" | grep -oE "$REGEX" | rev | cut -c -3 | rev)"
fi

INVENTORY="${PREFIX,,}"

[[ -z "$INVENTORY" ]] && die "EMPTY INVENTORY"

echo awx-cli host modify --enabled true -i "$INVENTORY" -n "$HOST" -v
awx-cli host modify --enabled true -i "$INVENTORY" -n "$HOST" -v
