#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2116,SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

$(code)bash

  $BIN ENVIRONMENT

$(code)

Get _AWX_ credentials for environment according \`~/.awx-config\`.

Example:

$(code)bash

  $BIN develop

$(code)

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


if [[ ! -z "$ANSIBLE_PASS_PASSWORD_STORE_DIR" ]]
then
  export PASSWORD_STORE_DIR="$ANSIBLE_PASS_PASSWORD_STORE_DIR"
fi

[[ -z "$1" ]] && die "EMPTY ENVIROMENT"

ENV="${1^^}"
USR="${ENV}_USER"
AWX_ENV="$(echo "${!ENV}")"
AWX_USER="$(echo "${!USR}")"
AWX_PASS=$(pass "$PASS_PREFIX/$AWX_ENV/awx/${AWX_USER}_password")

[[ -z "$AWX_PASS" ]] && die "EMPTY AWX_PASS"
echo "$AWX_PASS" | xclip -sel clip
