#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN JOB_ID

\`\`\`

Get \`stdout\` of _ad-hoc_ _job_.

Example:

\`\`\`bash

  $BIN 1234

	Enter passphrase for /tmp/awx_1234_l3bc_2qw/artifacts/1234/ssh_key_data:
	Identity added: /tmp/awx_1234_l3bc_2qw/artifacts/1234/ssh_key_data (/tmp/awx_1234_l3bc_2qw/artifacts/1234/ssh_key_data)
	sprn01dev | CHANGED | rc=0 >>
	Restarting cups (via systemctl): cups.service.


	OK. (changed: false)

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY JOB_ID"
JOB_ID="$1"

awx-cli ad_hoc stdout "$JOB_ID"
