#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN INVENTORY LIMIT USER REGEX

\`\`\`

Find _Firefox_ preferences

Example:

\`\`\`bash

  $BIN wst dev ansible 'network.proxy.*'

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY INVENTORY"
INVENTORY="$1"

[[ -z "$2" ]] && die "EMPTY LIMIT"
LIMIT="$2"

[[ -z "$3" ]] && die "EMPTY USER"
U="$3"

[[ -z "$4" ]] && die "EMPTY REGEX"
REGEX="$4"

COMMAND="/usr/bin/find \$(getent passwd \"$U\" | cut -d: -f6)/.mozilla/firefox/ -type f -iname '*.js' | /usr/bin/xargs grep -E '$REGEX'"

printf "## Execute $COMMAND in %s" "$LIMIT"
code
echo "  # awx-adhoc-shell $INVENTORY $LIMIT $COMMAND"
echo

awx-adhoc-shell "$INVENTORY" "$LIMIT" "$COMMAND"

code
