#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"
JSON_LIST="$(mktemp)"

[[ -z "$1" ]] && die "EMPTY VERSION"

#function get_url()
#{
#  local PATH
#
#  [[ "$1" = 'project'      ]] && PATH='#/projects/'
#  [[ "$1" = 'job_template' ]] && PATH='#/templates/job_template'
#  [[ "$1" = 'workflow'     ]] && PATH='#/templates/workflow_job_template'
#
#  printf "%s/%s/%s" "$AWX_CFG_HOST" "$PATH" "$2"
#}

PAD_LIMIT="$(awk '{print $2}' "$1" | wc -L)"

cat "$1" | while read TYPE NAME _
do
  ID="$(awx-cli $TYPE get -n $NAME -f id)"
  printf "%-*s %s\n" "$PAD_LIMIT" "$NAME" "$(get_url "$TYPE" "$ID")"
done
