#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2086

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:
  $BIN

Description

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die "EMPTY VERSION"

function get_last_job()
{
  [[ -z "$1" ]] && exit 1
  [[ -z "$2" ]] && exit 1
  TYPE="${1/_/-}"
  awx-$TYPE-get-last-job "$2"
}

TMP="$(mktemp)"

while read -r TYPE NAME _
do
  [[ "$TYPE" != 'workflow' ]] && continue
  ID="$(get_last_job "$TYPE" "$NAME")"
  awx-workflow-job-get "$ID"
done < "$1" | sort -k 4 | tee "$TMP"

TIMES="$(awk '{print $2}' "$TMP")"
TOTAL="$(timesum "$TIMES")"

printf "%20s %5s\\n" "" "$TOTAL"
