#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN INVENTORY LIMIT REGEX

\`\`\`

Filter /var/log/ipa-sss-syn.log by \`REGEX\` (Default current date) and
show the following colums:

  time user sAMAccountName sss_cache seconds

Example:

  $BIN ipa ipa

	14:57 user=root sAMAccountName=0227 sss_cache=0 seconds=1
	15:13 user=ansible sAMAccountName=3250 sss_cache=0 seconds=0
	15:40 user=root sAMAccountName=0282 sss_cache=0 seconds=0
	15:54 user=root sAMAccountName=0847 sss_cache=1 seconds=5
	16:08 user=rootansible sAMAccountName=3318 sss_cache=1 seconds=

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die "EMPTY INVENTORY"
INVENTORY="$1"

[[ -z "$2" ]] && die "EMPTY LIMIT"
LIMIT="$2"

[[ -n "$DATE"      ]] || DATE="$(date +%F)"
[[ -n "$LOG"       ]] || LOG='/var/log/ipa-sss-syn.log'
[[ -n "$REGEX"     ]] || REGEX="^$DATE"
[[ -z "$3"         ]] || REGEX="$3"
[[ -z "$REGEX"     ]] && die "EMPTY REGEX"

COMMAND="sudo /usr/bin/awk '/$REGEX/ {print \$2,\$3,\$4,\$19,\$NF}' $LOG"

printf "## Execute $COMMAND in %s" "$LIMIT"
echo
echo "\`\`\`"
echo
echo "  # awx-adhoc-shell $INVENTORY $LIMIT $COMMAND"
echo

awx-adhoc-shell "$INVENTORY" "$LIMIT" "$COMMAND"

echo
echo "\`\`\`"
