#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN PROJECT_NAME [TEAM|defaut_team] [TYPE|use]

\`\`\`

Grant permissions to a _team_ for a _project_.
Use default team defined in config and \`use\` as default permission.

\`\`\`bash

  $BIN ansible_wst_v1.0.0 devops

  Resource changed.
  ==== ==== ==== =======
   id  team type project
  ==== ==== ==== =======
  3268    7 use      727
  ==== ==== ==== =======

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

TEAM="$DEFAULT_TEAM"

[[ -z "$1" ]] && die 'EMPTY PROJECT_NAME'
PROJECT_NAME="$1"
TYPE='use'

[[ -z "$2"    ]] || TEAM="$2"
[[ -z "$3"    ]] || TYPE="$3"
[[ -z "$TEAM" ]] && die "EMPTY TEAM"

grant_project "$PROJECT_NAME" "$TEAM" "$TYPE"
