#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2001

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN JSON NEW_NAME

\`\`\`

Rename \`.json\` file and replace internal \`name\`.

Example:

\`\`\`bash

  $BIN pve_kvm.json pve_vms_kvm

\`\`\`
EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die "EMPTY FILE"
[[ -e "$1" ]] || die "NOT FOUND $1"
[[ -z "$2" ]] || NEW_NAME="$2"

[[ -z "$2" ]] && die "EMPTY NEW_NAME"

JSON="$1"
NAME="$(basename "$JSON" .json)"
NEW_JSON="$(echo "$JSON" | sed "s/$NAME/$NEW_NAME/g")"

echo "RENAME FROM $JSON TO $NEW_JSON"
echo
sed "s/$NAME/$NEW_NAME/g" "$JSON" > "$NEW_JSON"

LEN="$(grep -E '(unified_job_name|project)' "$NEW_JSON" | wc -c)"
WIDTH="$((LEN*2+10))"

diff -y --suppress-common-lines -W "$WIDTH" "$JSON" "$NEW_JSON"

echo
