#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2086

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:
  $BIN

Description

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die "EMPTY PROJECT NAME"
[[ -z "$2" ]] && die "EMPTY BRANCH"
BRANCH="$2"

[[ ! -z "$DEFAULT_ORGANIZATION"   ]] && ORGANIZATION="$DEFAULT_ORGANIZATION"
[[ ! -z "$DEFAULT_SCM_CREDENTIAL" ]] && SCM_CREDENTIAL="$DEFAULT_SCM_CREDENTIAL"

NAME="$1_$BRANCH"
[[ "$BRANCH" = 'master' ]] && NAME="$1"

URL="$SCM_URL_BASE/$1"

awx-cli project create               \
  --name "$NAME"                     \
  --description ""                   \
  --organization "$ORGANIZATION"     \
  --scm-type git                     \
  --scm-url "$URL"                   \
  --scm-branch "$BRANCH"             \
  --scm-credential "$SCM_CREDENTIAL" \
  --scm-clean false                  \
  --scm-delete-on-update true $AWX_DEBUG && project_update "$NAME"
