#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN WORKFLOW_JOB_ID

\`\`\`

Get summary of \`workflow_job\` execution.

Example:

\`\`\`bash

  $BIN

  awx-workflow-job-summary 143

  === ================== ====== ========== ======================== =======
  id         name         type    status           created          elapsed
  === ================== ====== ========== ======================== =======
  144 vms_bak_dsk_v0.3.0 job    successful 2021-11-30T18:54:13.7518 19.166
  146 vms_rbt_wfr_v0.1.0 job    successful 2021-11-30T18:54:33.5181 185.63
  147 vms_apt_upd_v0.1.0 job    successful 2021-11-30T18:57:39.7561 14.068
  149 vms_crn_rsy_v0.4.0 job    successful 2021-11-30T18:57:54.4358 18.851
  151 vms_nfs_own_v0.4.0 job    successful 2021-11-30T18:58:13.9210 24.452
  === ================== ====== ========== ======================== =======

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY WORKFLOW_JOB_ID"

WORKFLOW_JOB_ID="$1"

awx-cli workflow_job summary "$WORKFLOW_JOB_ID"
