#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2001

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN JOB_LOG_PATTERN

\`\`\`

Get group, description, inventory_host and last job of awx_history_stdout in multiples job \`.log\` files.

Example:

\`\`\`bash

  $BIN 12*.log

	dev wstdevelop01 wstdev01 wfw_wst_upd_v1.2.0
	dev wstdevelop02 wstdev02 wfw_wst_upd_v1.3.0

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage
LOGS='*.log'

[[ -n "$1" ]] && LOGS="$1"

for LOG in $LOGS
do

  awx-log-get-host-last-job "$LOG" | while read -r HOST VERSION
  do

    DESCRIPTION="$(awx-host-get-description "$HOST")"
    GROUP="$(awx-host-get-groups "$HOST" | grep -v 'wst')"

    echo "$GROUP $DESCRIPTION $HOST $VERSION"

  done

done | sort -u
