#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF

Usage:

\`\`\`bash

  $BIN WORKFLOW_JOB_ID

\`\`\`

Get enabled hosts of limit groups from workflow_job

Example:

\`\`\`bash

  $BIN 123

  dev wstdev01
  dev wstdev02
  dev wstdev03
  lab wstlab01
  lab wstlab02

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

INVENTORY="wst"

[[ -z "$1" ]] && die "EMPTY WORKFLOW_JOB_ID"

WORKFLOW_JOB_ID="$1"

awx-workflow-job-get-limit "$WORKFLOW_JOB_ID" \
  | while read -r GROUP
    do

			GROUP_ID="$(group_get_id "$INVENTORY" "$GROUP")"
      [[ -z "$GROUP_ID" ]] && continue

      awx-host-list-inventory-group "$INVENTORY" "$GROUP_ID" \
        | grep "$INVENTORY" | while read -r _ HOST
          do
            echo "$GROUP $HOST"
          done

    done
