#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN INVENTORY.json GROUP

\`\`\`

Get hosts from group of inventory \`.json\` file

Example:

\`\`\`bash

  $BIN inventory/pve.json dev

    spve01dev

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY INVENTORY"
[[ -e "$1" ]] || die "NOT FOUND $1"
INVENTORY="$1"

[[ -z "$2" ]] && die "EMPTY GROUP"
GROUP="$2"

JQ=".[] | .asset_relation.group[] | select(.name == \"$GROUP\") | .variables"

jq -r "$JQ" "$INVENTORY"
