#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1117
# shellcheck disable=SC2086

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\'\'\'bash

  $BIN JOB_TEMPLATE [TEAM]

\'\'\'

List

Example:

\'\'\'bash

  $BIN pve-udp-v0.1.0 devops

\'\'\'

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY JOB_TEMPLATE"
JOB_TEMPLATE="$1"
[[ -z "$2" ]] || TEAM="$2"

[[ -z "$TEAM" ]] && TEAM="$DEFAULT_TEAM"

awx-cli role list $AWX_DEBUG      \
  --all-pages                     \
  --job-template "$JOB_TEMPLATE"  \
  --team "$TEAM"                  \
    | grep 'job_template'         \
    | awk '{print $1,$2,$3}'
