#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null
# shellcheck disable=SC1117
# shellcheck disable=SC2086

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\'\'\'bash

  $BIN WORKFLOW [TEAM]

\'\'\'

Show the permissions of a _workflow_ for a _team_.
By default output is a CSV, you can enable Markdown output.

Example:

\'\'\'bash

  $BIN wfw_pve_kvm_v0.1.0 devops

    workflow,wfw_pve_kvm_v0.1.0,Execute,devops

  MD_TABLE=1 awx-role-list-workflow wfw_pve_kvm_v0.1.0 devops

    | _workflow_           | \`wfw_pve_kvm_v0.1.0                    \` | _Execute_  | _devops_             |

\'\'\'

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1"        ]] && die "EMPTY WORKFLOW"
WORKFLOW="$1"
[[ -z "$2"        ]] || TEAM="$2"
[[ -z "$TEAM"     ]] && TEAM="$DEFAULT_TEAM"
[[ -n "$MD_TABLE" ]] || MD_TABLE=0

RESOURCE_TYPE='workflow'
RESOURCE_NAME="$WORKFLOW"
TYPE="$(role_list_team_workflow "$TEAM" "$WORKFLOW")"
[[ -z "$TYPE" ]] && exit 1

ROLE_LIST_FUNC='role_list_team_csv'
[[ "$MD_TABLE" -eq 1 ]] && ROLE_LIST_FUNC='role_list_team_table'
$ROLE_LIST_FUNC "$RESOURCE_TYPE" "$RESOURCE_NAME" "$TYPE" "$TEAM"
