#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2001

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN JSON

$(code)

Increment semantic version in \`.json\` file.

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

VERSION='bug'

[[ -z "$1" ]] && die "EMPTY FILE"
[[ -e "$1" ]] || die "NOT FOUND $1"
[[ -z "$2" ]] || VERSION="$2"

JSON="$1"
NAME="$(basename "$JSON" .json)"
NUMBER="$(echo "$NAME" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')"
NEW_NUMBER="$(bump-version "$NUMBER" "$VERSION")"

# FIXME NEW_NAME="$(echo "$NAME" | sed "s/$NUMBER/$NEW_NUMBER/g")"
NEW_JSON="$(echo "$JSON" | sed "s/$NUMBER/$NEW_NUMBER/g")"

LEN="$(wc -L "$JSON" | cut -d' ' -f1)"
WIDTH="$((LEN+10))"

echo "BUMP VERSION FROM $JSON TO $NEW_JSON"
# FIXME BRANCH="$(cat "$JSON" | jq -r '.[] | .scm_branch')"
# FIXME NEW_BRANCH="$(echo "$BRANCH" | sed "s/$NUMBER/$NEW_NUMBER/g")"
echo
sed "s/$NUMBER/$NEW_NUMBER/g" "$JSON" > "$NEW_JSON"

diff -y --suppress-common-lines -W "$WIDTH" "$JSON" "$NEW_JSON"

echo
