#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

List all _job_templates_ names.

Example:

\`\`\`bash

  $BIN

  pve_kvm_v0.1.0

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

FIRST="$(mktemp)"

awx-cli job_template list \
  --format json           \
  --page 1                \
  --page-size 1           > "$FIRST"

TOTAL_TPLS="$(jq -r .count "$FIRST")"
printf "TOTAL JOB_TEMPLATES: %s\\n" "$TOTAL_TPLS" 1>&2

[[ -n "$JQ" ]] || JQ='.results[].name'

awx-cli job_template list -a -f json | jq -r "$JQ" | sort

rm -f "$FIRST"
