#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2002

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN [INVENTORY]

$(code)

Disable all enabled hosts in _inventory_.

Example:

\`\`\`bash

  $BIN pve

$(code)

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

HOST_IDS="$(mktemp)"

[[ -z "$1" ]] && die "EMPTY INVENTORY"
INVENTORY="$1"
INVENTORY_ID="$(inventory_get_id "$INVENTORY")"
[[ -z "$INVENTORY_ID" ]] && exit 1

host_list_enabled "$INVENTORY_ID" > "$HOST_IDS"

TOTAL="$(cat "$HOST_IDS" | wc -l)"

if [[ "$TOTAL" -eq 0 ]]
then
  stderror "NOTHING TO DO"
  exit 0
fi

printf "FOUND %0d HOSTS TO DISABLE\\n" "$TOTAL"

while read -r HOST_ID
do

  if [[ "$HOST_ID" =~ [0-9]+ ]]
  then
    host_disable "$INVENTORY_ID" "$HOST_ID"
  fi

done < "$HOST_IDS"

rm -f "$HOST_IDS"
