#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:
  $BIN

Description

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die "EMPTY HOST"
[[ -z "$2" ]] && die "EMPTY VARIABLE"
[[ -z "$3" ]] && die "EMPTY VALUE"

HOST="$1"
VARIABLE="$2"
NEW_VALUE="$3"
PREFIX="${HOST//-*/}"
INVENTORY="${PREFIX,,}"

JSON=$(mktemp --suffix .json)

awx-cli host get            \
  --format json             \
  --inventory "$INVENTORY"  \
  --name "$HOST"            > "$JSON" 2>/dev/null

YAML="$(mktemp --suffix .yml)"

[[ -s "$JSON" ]] || die "EMPTY JSON"

jq -r .variables "$JSON" | yq -r . > "$YAML" 2>/dev/null

[[ -s "$YAML" ]] || die "EMPTY YAML"

VALUE="$(yq -r ".$VARIABLE" "$YAML" | grep -vi null)"

title2 "MODIFY $VARIABLE WITH $NEW_VALUE IN $HOST FROM $INVENTORY INVENTORY"

code
if [[ "$VALUE" = "$NEW_VALUE" ]]
then
  echo "ALREADY SET $VARIABLE = $NEW_VALUE"
else

  jq_yq_modify "$YAML" "$VARIABLE" "$NEW_VALUE"

  [[ -s "$YAML" ]] || die "EMPTY YAML"

  awx-cli host modify        \
    --inventory "$INVENTORY" \
    --name "$HOST"           \
    --variables "@$YAML"

fi
code

rm -f "$JSON"
rm -f "$YAML"
