#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF

Usage:

\`\`\`bash

  $BIN HOST GROUP_NAME [INVENTORY]

\`\`\`bash

Associate _host_ to _group_.
Use PREFIX-HOST as INVENTORY.

\`\`\`bash

  $BIN wst-dev01 dev

  $BIN wstdev01 dev wst

\`\`\`
EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage


[[ -z "$1" ]] && die "EMPTY HOSTNAME"

HOST="$1"
PREFIX="${HOST//-*/}"
INVENTORY="${PREFIX,,}"
[[ -z "$3" ]] || INVENTORY="$3"

[[ -z "$2" ]] && die "EMPTY GROUP NAME"
GROUP="$2"

HOST_ID="$(awx-cli host get -i "$INVENTORY" -n "$HOST" -f id)"
GROUP_ID="$(group_get_id "$INVENTORY" "$GROUP")"

[[ -z "$GROUP_ID" ]] && die "NOT FOUND GROUP_ID FOR GROUP $GROUP"
[[ -z "$HOST_ID"  ]] && die "NOT FOUND HOST_ID FOR HOST $HOST"

awx-cli host associate      \
  --host "$HOST_ID"         \
  --group "$GROUP_ID"       \
