#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2001
# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN HOST_VARS_YAML

\`\`\`

Generate _SSH_ host config from host_vars _YAML_ file.

Example:

\`\`\`bash

  $BIN host_vars/wstdev01.yml

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1" ]] && die "EMPTY HOST VARS YAML"
[[ -e "$1" ]] || die "NOT FOUND FILE $1"

YML="$1"

NAME="$(basename "$YML" .yml)"
HOST="$(yq -r .ansible_host "$YML")"

echo "Host $NAME"
echo "     Hostname $HOST"
echo

[[ "$HOST" =  "$NAME" ]] && exit 0
[[ "$HOST" =~ ^[0-9]+ ]] && exit 0

echo "Host $HOST"
echo "     Hostname $HOST"
echo
