#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2002

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN [JSON]

\`\`\`

Send to _AWX_ one or multiples _workflow_ and _workflows_ dependencies.

Without file, scan \`.json\` files with \`WORKFLOW_PREFIX\` in
\`WORKDIR\`.

Default Variables in \`~/.awx-config\`

\`\`\`ini

  DIR_WORKFLOW: workflow
  WORKFLOW_PREFIX: wfw

\`\`\`

Example:

\`\`\`bash

  $BIN workflow/wfw_pve_v0.1.0.json

\`\`\`
EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -d "$DIR_WORKFLOW" ]] || die "NOT FOUND DIRECTORY $PWD/$DIR_WORKFLOW"

JSON_LIST="$(mktemp)"
JSON_ALL="$(mktemp)"

if [[ -z "$1" ]]
then
  wait_seconds projects
  filelist_workflows > "$JSON_LIST"
else
  [[ -e "$1" ]] || die "NOT FOUND FILE $1"
  echo "$1" > "$JSON_LIST"
fi

cat "$JSON_LIST" | while read -r FILE
do
  get_json_workflows "$FILE"
done | awk '!seen[$0]++' > "$JSON_ALL"

filelist_total "$JSON_ALL" 'workflows'
filelist_send_all "$JSON_ALL"
