#!/bin/bash -x

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN [JSON]

\`\`\`

Send one _project_ \`.json\` file or send all _projects_ in _projects_
directory

\`\`\`bash

  $BIN projects/ansible_promox_v0.1.0.json

\`\`\`

EOF
exit 0
}


[[ -d "$DIR_PROJECT" ]] || die "NOT FOUND $PWD/$DIR_PROJECT"

JSON_LIST="$(mktemp)"

if [[ -z "$1" ]]
then
  wait_seconds projects
  filelist_projects > "$JSON_LIST"
  filelist_total "$JSON_LIST" 'projects'
else
  [[ -e "$1" ]] || die "NOT FOUND $1"
  echo "$1" > "$JSON_LIST"
fi

filelist_send_all "$JSON_LIST"
