#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2023 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2023 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null
# shellcheck disable=SC2001

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN JSON [NEW_BRANCH]

\`\`\`

Get \`scm_branch\` in all JSONs in list file.

Example:

\`\`\`bash

  $BIN project/inventory_v0.7.13.json

	v0.7.13 project/inventory_v0.7.13.json

\`\`\`
EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

TMPI="$(mktemp)"
true > "$TMPI"

if [[ ! -t 0 ]]
then

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

fi

[[ -z "$1"    ]] || echo "$1" > "$TMPI"
[[ -s "$TMPI" ]] || die "EMPTY FILE $TMPI"

while read -r JSON EXTRA
do

  if [[ ! -e "$JSON" ]]
  then
    echo >&2 "NOT FOUND FILE $JSON"
    continue
  fi

  SCM_BRANCH="$(jq -r '.[].scm_branch' "$JSON")"
  printf "%s %s %s\\n" "$SCM_BRANCH" "$JSON" "$EXTRA"

done < "$TMPI"

rm -f "$TMPI"
