#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

BIN="$(basename "$0")"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

List remote branchs of git repository.

Example:

\`\`\`bash

  $BIN

  master
  develop

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

REPO="$1"

if [[ -z "$1" ]]
then
  [[ -d "$PWD/.git" ]] || exit 1
  REPO="$(git remote get-url origin)"
fi

[[ -z "$REPO" ]] && exit 1
# BASED ON:
# https://stackoverflow.com/questions/10649814/get-last-git-tag-from-a-remote-repo-without-cloning

git ls-remote --heads "$REPO" | awk '{print $2}' | cut -d/ -f3- | tr -d '^{}' | sort -u | sort -Vr
