#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

List projects from Gitlab API.

Example:

\`\`\`bash

  $BIN

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ ! -z "$GITLAB_CI_TOKEN" ]] && TOKEN="$GITLAB_CI_TOKEN"
[[ -z "$TOKEN" ]] && die "NOT FOUND TOKEN"

function get_projects()
{

local PAGE=1
[[ ! -z "$1" ]] && PAGE="$1"

URL="$SCM_URL_API/projects?page=$PAGE&per_page=100&membership=true"
JSON="git-projects-${PAGE}.json"

curl -s -k --header "PRIVATE-TOKEN: $TOKEN" "$URL" | jq -r > "$JSON"

MSG="$(jq -r .message "$JSON")"

[[ "$MSG" =~ ^401.* ]] && die "$MSG"

jq -r '.' "$JSON" \
  | jq -r '.[] | "\(.name) \(.ssh_url_to_repo) \(.description)"'

}

get_projects 1
get_projects 2
