#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

Description

Example:

\`\`\`bash

  $BIN

\`\`\`

EOF
exit 0
}

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

[[ -n "$JOB_ID" ]] || JOB_ID="$1"
[[ -z "$JOB_ID" ]] && die "EMPTY JOB_ID"

awx_cfg_read

[[ -n "$URL_BASE" ]] || URL_BASE="$AWX_CFG_HOST/#/jobs/playbook"

printf "[job %s](%s/%s)\\n" "$JOB_ID" "$URL_BASE" "$JOB_ID"
