#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN SYSLOGFILE

\`\`\`

    DATE="$(echo "$LINE" | cut -c -15)"
    HOST="$(echo "$LINE" | awk '{print $4}')"
    VMID="$(echo "$LINE" | grep -oE 'vmid=[0-9]+')"
    STATE="$(echo "$LINE" | grep -oE 'state=[a-z]+')"
    printf "%s %s ansible-proxmox_kvm: %s %s\\n" "$DATE" "$HOST" "$VMID" "$STATE"

0
Read a \`syslog\` and return lines match with \`ansible-proxmox_kvm\`,
summary columns _date_, _host_, _vmid_ and _state_.

Example:

\`\`\`bash

  $BIN /var/log/syslog

	Mar 23 16:34:36 spve-dev ansible-proxmox_kvm: vmid=900 state=present

\`\`\`

EOF
exit 0
}

if [[ -n "$1" ]]
then
  log_ansible_proxmox_kvm "$1"
else
  get_file_list 'syslog*' | while read -r FILE
  do
    log_ansible_proxmox_kvm "$FILE"
  done
fi
