#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

BIN="$(basename "$0")"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

Update to last tag in \`version:\` of each repository in
\`requirements.yml\`.

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

cd "$PWD" || exit 1
YML='requirements.yml'

[[ ! -e "$YML" ]] && exit 1

TMP=$(mktemp)

grep 'src:' "$YML" | awk '{print $3}' | while read -r REPO
do
  LAST_TAG=$(git-ls-remote-tags "$REPO" | head -1)
  NAME=$(grep -A3 "$REPO" "$YML" | grep name: | awk '{print $2}')

YAML=$(cat << EOF
- src: $REPO
  scm: git
  version: $LAST_TAG
  name: $NAME
EOF

)

echo "$YAML"

done > "$TMP" && mv -f "$TMP" "$YML"
