#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2181
# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF

Usage:

\`\`\`bash

  $BIN YAML_FILE [KEYS_FILE]

\`\`\`bash

Search variables values in \`.yml\` using keys file.

\`\`\`

Example:

\`\`\`bash

  $BIN group_vars/apt.yml keys_to_search

	apt_setup_proxy: true
	apt_setup_proxy_ip: 10.10.0.1
	apt_setup_proxy_port: 3142

\`\`\`
EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -z "$1"    ]] || YAML="$1"
[[ -z "$2"    ]] || KEYS="$2"
[[ -e "$YAML" ]] || exit 1
[[ -e "$KEYS" ]] || exit 1

while read -r KEY
do

  VALUE="$(grep -E "^$KEY:" "$YAML" | cut -d: -f2- | sed 's/^ //g')"
  [[ -z "$VALUE" ]] && VALUE='null'
  echo "$KEY: $VALUE"

done < "$KEYS"
