#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/awx-common"

function usage()
{
cat << EOF

Usage:

\`\`\`bash

  $BIN [DIRECTORY]

\`\`\`bash

Get \`role_name\` from \`meta/main.yml\`.

\`\`\`

Example:

\`\`\`bash

  $BIN

\`\`\`
EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

TMPI="$(mktemp)"

if [[ ! -t 0 ]]
then

  true > "$TMPI"

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

fi

[[ -z "$1"    ]] && echo "$PWD" > "$TMPI"
[[ -n "$JQ"   ]] || JQ='.galaxy_info.role_name'

while read -r DIR
do

  if [[ ! -d "$DIR" ]]
  then
    stderror "NOT FOUND DIRECTORY: $DIR"
    continue
  fi

  MAIN="$DIR/meta/main.yml"

  if [[ ! -e "$MAIN" ]]
  then
    stderror "NOT FOUND FILE: $MAIN"
    continue
  fi

  yq -r "$JQ" "$MAIN"

done < "$TMPI"

rm -f "$TMPI"
